FROM ianwalter/puppeteer:latest
WORKDIR /app
ADD . /app

RUN curl -s https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list && apt-get update && apt-get install -y google-chrome-stable
RUN npm install

CMD npx wdio grid-docker-wdio.conf