# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#       run: docker compose up --exit-code-from runtests
name: WebDriverIO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runtests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: SetUp NodeJs
      uses: actions/setup-node@v1
      with:
        node-version: 14.18.1

    - uses: actions/checkout@v2
    - name: Run docker compose 
      run: docker compose up

    - uses: actions/checkout@v2
    - name: Run tests
      run: npx wdio grid-docker-wdio.conf.js
    